// <auto-generated />
namespace Mvc5.App.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitalDBcreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitalDBcreation));
        
        string IMigrationMetadata.Id
        {
            get { return "201602031944187_Inital DB creation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
